// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// General Purpose Input/Output module

`include "prim_assert.sv"

module gpio
  import gpio_pkg::*;
  import gpio_reg_pkg::*;
#(
  parameter logic [NumAlerts-1:0] AlertAsyncOn = {NumAlerts{1'b1}},
  parameter bit GpioAsHwStrapsEn = 1,
  // This parameter instantiates 2-stage synchronizers on all GPIO inputs.
  parameter bit GpioAsyncOn = 1
) (
  input clk_i,
  input rst_ni,

  // Strap sampling trigger and broadcast output
  input strap_en_i,
  output gpio_straps_t sampled_straps_o,

  // Bus interface
  input  tlul_pkg::tl_h2d_t tl_i,
  output tlul_pkg::tl_d2h_t tl_o,

  // Interrupts
  output logic [31:0] intr_gpio_o,

  // Alerts
  input  prim_alert_pkg::alert_rx_t [NumAlerts-1:0] alert_rx_i,
  output prim_alert_pkg::alert_tx_t [NumAlerts-1:0] alert_tx_o,

  // GPIOs
  input        [31:0] cio_gpio_i,
  output logic [31:0] cio_gpio_o,
  output logic [31:0] cio_gpio_en_o
);



  gpio_reg2hw_t reg2hw;
  gpio_hw2reg_t hw2reg;

  logic [31:0] cio_gpio_q;
  logic [31:0] cio_gpio_en_q;

  // possibly filter the input based upon register configuration
  logic [31:0] data_in_d;
  localparam int unsigned CntWidth = 4;
  for (genvar i = 0 ; i < 32 ; i++) begin : gen_filter
    prim_filter_ctr #(
      .AsyncOn(GpioAsyncOn),
      .CntWidth(CntWidth)
    ) u_filter (
      .clk_i,
      .rst_ni,
      .enable_i(reg2hw.ctrl_en_input_filter.q[i]),
      .filter_i(cio_gpio_i[i]),
      .thresh_i({CntWidth{1'b1}}),
      .filter_o(data_in_d[i])
    );
  end



  if (GpioAsHwStrapsEn) begin : gen_strap_sample
    // sample at gpio inputs at strap_en_i signal pulse.
    logic strap_en;

    // The strap_en_i is a single cycle pulse generated by the pwrmgr
    // Both sender (pwrmgr) and receiver (gpio controller) are in the same clock domain (io_div4)
    // A cdc synchronizer is not required
    //
    assign strap_en = strap_en_i;

    // we guarantee here by design that this will always be done exactly once per reset cycle.
    logic sample_trigger;
    assign sample_trigger                    = strap_en && !reg2hw.hw_straps_data_in_valid.q;
    assign hw2reg.hw_straps_data_in_valid.de = sample_trigger;
    assign hw2reg.hw_straps_data_in_valid.d  = 1'b1;
    assign hw2reg.hw_straps_data_in.de       = sample_trigger;
    assign hw2reg.hw_straps_data_in.d        = data_in_d;
    assign sampled_straps_o.data             = reg2hw.hw_straps_data_in.q;
    assign sampled_straps_o.valid            = reg2hw.hw_straps_data_in_valid.q;
    `ASSUME(StrapSampleOnce_A, ##1 $fell(sample_trigger) |-> always !sample_trigger)
  end else begin : gen_no_strap_sample
    assign hw2reg.hw_straps_data_in_valid.de = 1'b0;
    assign hw2reg.hw_straps_data_in_valid.d  = 1'b0;
    assign hw2reg.hw_straps_data_in.de       = 1'b0;
    assign hw2reg.hw_straps_data_in.d        = '0;
    assign sampled_straps_o.data             = '0;
    assign sampled_straps_o.valid            = 1'b0;

    logic unused_signals;
    assign unused_signals = ^{strap_en_i,
                              reg2hw.hw_straps_data_in.q,
                              reg2hw.hw_straps_data_in_valid.q};
  end

  // GPIO_IN
  assign hw2reg.data_in.de = 1'b1;
  assign hw2reg.data_in.d  = data_in_d;

  // GPIO_OUT
  assign cio_gpio_o                     = cio_gpio_q;
  assign cio_gpio_en_o                  = cio_gpio_en_q;

  assign hw2reg.direct_out.d            = cio_gpio_q;
  assign hw2reg.masked_out_upper.data.d = cio_gpio_q[31:16];
  assign hw2reg.masked_out_upper.mask.d = 16'h 0;
  assign hw2reg.masked_out_lower.data.d = cio_gpio_q[15:0];
  assign hw2reg.masked_out_lower.mask.d = 16'h 0;

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      cio_gpio_q  <= '0;
    end else if (reg2hw.direct_out.qe) begin
      cio_gpio_q <= reg2hw.direct_out.q;
    end else if (reg2hw.masked_out_upper.data.qe) begin
      cio_gpio_q[31:16] <=
        ( reg2hw.masked_out_upper.mask.q & reg2hw.masked_out_upper.data.q) |
        (~reg2hw.masked_out_upper.mask.q & cio_gpio_q[31:16]);
    end else if (reg2hw.masked_out_lower.data.qe) begin
      cio_gpio_q[15:0] <=
        ( reg2hw.masked_out_lower.mask.q & reg2hw.masked_out_lower.data.q) |
        (~reg2hw.masked_out_lower.mask.q & cio_gpio_q[15:0]);
    end
  end

  // GPIO OE
  assign hw2reg.direct_oe.d = cio_gpio_en_q;
  assign hw2reg.masked_oe_upper.data.d = cio_gpio_en_q[31:16];
  assign hw2reg.masked_oe_upper.mask.d = 16'h 0;
  assign hw2reg.masked_oe_lower.data.d = cio_gpio_en_q[15:0];
  assign hw2reg.masked_oe_lower.mask.d = 16'h 0;

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      cio_gpio_en_q  <= '0;
    end else if (reg2hw.direct_oe.qe) begin
      cio_gpio_en_q <= reg2hw.direct_oe.q;
    end else if (reg2hw.masked_oe_upper.data.qe) begin
      cio_gpio_en_q[31:16] <=
        ( reg2hw.masked_oe_upper.mask.q & reg2hw.masked_oe_upper.data.q) |
        (~reg2hw.masked_oe_upper.mask.q & cio_gpio_en_q[31:16]);
    end else if (reg2hw.masked_oe_lower.data.qe) begin
      cio_gpio_en_q[15:0] <=
        ( reg2hw.masked_oe_lower.mask.q & reg2hw.masked_oe_lower.data.q) |
        (~reg2hw.masked_oe_lower.mask.q & cio_gpio_en_q[15:0]);
    end
  end

  logic [31:0] data_in_q;
  always_ff @(posedge clk_i) begin
    data_in_q <= data_in_d;
  end

  logic [31:0] event_intr_rise, event_intr_fall, event_intr_actlow, event_intr_acthigh;
  logic [31:0] event_intr_combined;

  // instantiate interrupt hardware primitive
  prim_intr_hw #(.Width(32)) intr_hw (
    .clk_i,
    .rst_ni,
    .event_intr_i           (event_intr_combined),
    .reg2hw_intr_enable_q_i (reg2hw.intr_enable.q),
    .reg2hw_intr_test_q_i   (reg2hw.intr_test.q),
    .reg2hw_intr_test_qe_i  (reg2hw.intr_test.qe),
    .reg2hw_intr_state_q_i  (reg2hw.intr_state.q),
    .hw2reg_intr_state_de_o (hw2reg.intr_state.de),
    .hw2reg_intr_state_d_o  (hw2reg.intr_state.d),
    .intr_o                 (intr_gpio_o)
  );

  // detect four possible individual interrupts
  assign event_intr_rise    = (~data_in_q &  data_in_d) & reg2hw.intr_ctrl_en_rising.q;
  assign event_intr_fall    = ( data_in_q & ~data_in_d) & reg2hw.intr_ctrl_en_falling.q;
  assign event_intr_acthigh =                data_in_d  & reg2hw.intr_ctrl_en_lvlhigh.q;
  assign event_intr_actlow  =               ~data_in_d  & reg2hw.intr_ctrl_en_lvllow.q;

  assign event_intr_combined = event_intr_rise   |
                               event_intr_fall   |
                               event_intr_actlow |
                               event_intr_acthigh;

  // Alerts
  logic [NumAlerts-1:0] alert_test, alerts;
  assign alert_test = {
    reg2hw.alert_test.q &
    reg2hw.alert_test.qe
  };

  for (genvar i = 0; i < NumAlerts; i++) begin : gen_alert_tx
    prim_alert_sender #(
      .AsyncOn(AlertAsyncOn[i]),
      .IsFatal(1'b1)
    ) u_prim_alert_sender (
      .clk_i,
      .rst_ni,
      .alert_test_i  ( alert_test[i] ),
      .alert_req_i   ( alerts[0]     ),
      .alert_ack_o   (               ),
      .alert_state_o (               ),
      .alert_rx_i    ( alert_rx_i[i] ),
      .alert_tx_o    ( alert_tx_o[i] )
    );
  end

  // Register module
  gpio_reg_top u_reg (
    .clk_i,
    .rst_ni,

    .tl_i,
    .tl_o,

    .reg2hw,
    .hw2reg,

    // SEC_CM: BUS.INTEGRITY
    .intg_err_o (alerts[0])
  );

  // Assert Known: Outputs
  `ASSERT_KNOWN(IntrGpioKnown, intr_gpio_o)
  `ASSERT_KNOWN(CioGpioEnOKnown, cio_gpio_en_o)
  `ASSERT_KNOWN(CioGpioOKnown, cio_gpio_o)
  `ASSERT_KNOWN(AlertsKnown_A, alert_tx_o)

  // Alert assertions for reg_we onehot check
  `ASSERT_PRIM_REG_WE_ONEHOT_ERROR_TRIGGER_ALERT(RegWeOnehotCheck_A, u_reg, alert_tx_o[0])
// AUTO-GENERATED ASSERTIONS START

// Helper logic for masked access
logic [15:0] upper_mask_out_active;
logic [15:0] lower_mask_out_active;
logic [15:0] upper_mask_oe_active;
logic [15:0] lower_mask_oe_active;
logic strap_en;

// Strap enable assignment
assign strap_en = strap_en_i;

genvar i;
generate
  for (i = 0; i < 16; i++) begin : gen_mask_bits
    assign upper_mask_out_active[i] = reg2hw.masked_out_upper.mask.q[i] & reg2hw.masked_out_upper.data.qe;
    assign lower_mask_out_active[i] = reg2hw.masked_out_lower.mask.q[i] & reg2hw.masked_out_lower.data.qe;
    assign upper_mask_oe_active[i] = reg2hw.masked_oe_upper.mask.q[i] & reg2hw.masked_oe_upper.data.qe;
    assign lower_mask_oe_active[i] = reg2hw.masked_oe_lower.mask.q[i] & reg2hw.masked_oe_lower.data.qe;
  end
endgenerate

// CHK1: Direct output write
property p_direct_out_write;
  @(posedge clk_i) disable iff (!rst_ni)
  reg2hw.direct_out.qe |=> cio_gpio_q == $past(reg2hw.direct_out.q);
endproperty
CHK1_DirectOutWrite: assert property(p_direct_out_write);

// CHK2: Masked output upper
property p_masked_out_upper;
  @(posedge clk_i) disable iff (!rst_ni)
  reg2hw.masked_out_upper.data.qe |=> 
    ((cio_gpio_q[31:16] & reg2hw.masked_out_upper.mask.q) == 
     ($past(reg2hw.masked_out_upper.data.q) & $past(reg2hw.masked_out_upper.mask.q)));
endproperty
CHK2_MaskedOutUpper: assert property(p_masked_out_upper);

// CHK3: Masked output lower
property p_masked_out_lower;
  @(posedge clk_i) disable iff (!rst_ni)
  reg2hw.masked_out_lower.data.qe |=> 
    ((cio_gpio_q[15:0] & reg2hw.masked_out_lower.mask.q) == 
     ($past(reg2hw.masked_out_lower.data.q) & $past(reg2hw.masked_out_lower.mask.q)));
endproperty
CHK3_MaskedOutLower: assert property(p_masked_out_lower);

// CHK4: Direct OE write
property p_direct_oe_write;
  @(posedge clk_i) disable iff (!rst_ni)
  reg2hw.direct_oe.qe |=> cio_gpio_en_q == $past(reg2hw.direct_oe.q);
endproperty
CHK4_DirectOEWrite: assert property(p_direct_oe_write);

// CHK5: Masked OE upper
property p_masked_oe_upper;
  @(posedge clk_i) disable iff (!rst_ni)
  reg2hw.masked_oe_upper.data.qe |=> 
    ((cio_gpio_en_q[31:16] & reg2hw.masked_oe_upper.mask.q) == 
     ($past(reg2hw.masked_oe_upper.data.q) & $past(reg2hw.masked_oe_upper.mask.q)));
endproperty
CHK5_MaskedOEUpper: assert property(p_masked_oe_upper);

// CHK6: Masked OE lower
property p_masked_oe_lower;
  @(posedge clk_i) disable iff (!rst_ni)
  reg2hw.masked_oe_lower.data.qe |=> 
    ((cio_gpio_en_q[15:0] & reg2hw.masked_oe_lower.mask.q) == 
     ($past(reg2hw.masked_oe_lower.data.q) & $past(reg2hw.masked_oe_lower.mask.q)));
endproperty
CHK6_MaskedOELower: assert property(p_masked_oe_lower);

// CHK7: GPIO output drive
generate
  for (i = 0; i < 32; i++) begin : gen_output_drive_check
    property p_gpio_output_drive_i;
      @(posedge clk_i) disable iff (!rst_ni)
      cio_gpio_en_o[i] |-> (cio_gpio_o[i] == cio_gpio_q[i]);
    endproperty
    CHK7_GpioOutputDrive_i: assert property(p_gpio_output_drive_i);
  end
endgenerate

// CHK8: GPIO output tristate
generate
  for (i = 0; i < 32; i++) begin : gen_tristate_check
    property p_gpio_output_tristate_i;
      @(posedge clk_i) disable iff (!rst_ni)
      !cio_gpio_en_q[i] |-> !cio_gpio_en_o[i];
    endproperty
    CHK8_GpioOutputTristate_i: assert property(p_gpio_output_tristate_i);
  end
endgenerate

// CHK9: Input data direct
generate
  for (i = 0; i < 32; i++) begin : gen_input_direct_check
    property p_input_data_direct_i;
      @(posedge clk_i) disable iff (!rst_ni)
      (!reg2hw.ctrl_en_input_filter.q[i]) |-> (data_in_d[i] == cio_gpio_i[i]);
    endproperty
    CHK9_InputDataDirect_i: assert property(p_input_data_direct_i);
  end
endgenerate

// CHK10: Input data filtered
generate
  for (i = 0; i < 32; i++) begin : gen_input_filtered_check
    property p_input_data_filtered_i;
      @(posedge clk_i) disable iff (!rst_ni)
      (reg2hw.ctrl_en_input_filter.q[i] && $stable(cio_gpio_i[i])[*16]) |-> 
        (data_in_d[i] == cio_gpio_i[i]);
    endproperty
    CHK10_InputDataFiltered_i: assert property(p_input_data_filtered_i);
  end
endgenerate

// CHK11: HW strap sampling
property p_hw_strap_sampling;
  @(posedge clk_i) disable iff (!rst_ni)
  (strap_en && !reg2hw.hw_straps_data_in_valid.q) |=> 
    (reg2hw.hw_straps_data_in.q == $past(cio_gpio_i));
endproperty
CHK11_HWStrapSampling: assert property(p_hw_strap_sampling);

// CHK12-17: Interrupt related assertions
generate
  for (i = 0; i < 32; i++) begin : gen_intr_assertions
    // CHK12: Interrupt rising edge
    property p_intr_rising_edge_i;
      @(posedge clk_i) disable iff (!rst_ni)
      (reg2hw.intr_ctrl_en_rising.q[i] && !data_in_q[i] && data_in_d[i]) |-> 
        event_intr_rise[i];
    endproperty
    CHK12_IntrRisingEdge_i: assert property(p_intr_rising_edge_i);

    // CHK13: Interrupt falling edge
    property p_intr_falling_edge_i;
      @(posedge clk_i) disable iff (!rst_ni)
      (reg2hw.intr_ctrl_en_falling.q[i] && data_in_q[i] && !data_in_d[i]) |-> 
        event_intr_fall[i];
    endproperty
    CHK13_IntrFallingEdge_i: assert property(p_intr_falling_edge_i);

    // CHK14: Interrupt level high
    property p_intr_level_high_i;
      @(posedge clk_i) disable iff (!rst_ni)
      (reg2hw.intr_ctrl_en_lvlhigh.q[i] && data_in_d[i]) |-> 
        event_intr_acthigh[i];
    endproperty
    CHK14_IntrLevelHigh_i: assert property(p_intr_level_high_i);

    // CHK15: Interrupt level low
    property p_intr_level_low_i;
      @(posedge clk_i) disable iff (!rst_ni)
      (reg2hw.intr_ctrl_en_lvllow.q[i] && !data_in_d[i]) |-> 
        event_intr_actlow[i];
    endproperty
    CHK15_IntrLevelLow_i: assert property(p_intr_level_low_i);

    // CHK16: Interrupt enable mask
    property p_intr_enable_mask_i;
      @(posedge clk_i) disable iff (!rst_ni)
      intr_gpio_o[i] |-> (reg2hw.intr_state.q[i] && reg2hw.intr_enable.q[i]);
    endproperty
    CHK16_IntrEnableMask_i: assert property(p_intr_enable_mask_i);

  end
endgenerate

// AUTO-GENERATED ASSERTIONS END
// Stage 1 AUTO-GENERATED ASSERTIONS START

// SVA to ensure cio_gpio_q is reset to 0 (LINE 1)
  property p_cio_gpio_q_reset;
    @(posedge clk_i) disable iff (!rst_ni)
    !rst_ni |-> cio_gpio_q == '0;
  endproperty
  A_cio_gpio_q_reset: assert property (p_cio_gpio_q_reset);

  // SVA to ensure cio_gpio_en_q is reset to 0 (LINE 5)
  property p_cio_gpio_en_q_reset;
    @(posedge clk_i) disable iff (!rst_ni)
    !rst_ni |-> cio_gpio_en_q == '0;
  endproperty
  A_cio_gpio_en_q_reset: assert property (p_cio_gpio_en_q_reset);

  // SVA for Direct Output Enable Control (LINE 6)
  property p_direct_oe_control;
    @(posedge clk_i) disable iff (!rst_ni)
    reg2hw.direct_oe.qe |=> cio_gpio_en_q == reg2hw.direct_oe.q;
  endproperty
  A_direct_oe_control: assert property (p_direct_oe_control);

  //Helper logic for the current value of cio_gpio_q
  logic [31:0] pre_cio_gpio_q;
  always_ff @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      pre_cio_gpio_q <= '0;
    else
      pre_cio_gpio_q <= cio_gpio_q;

  // SVA for Masked Write Verification (Data) Upper (LINE 3)
  property p_masked_write_data_upper;
    @(posedge clk_i) disable iff (!rst_ni)
    reg2hw.masked_out_upper.data.qe |=>
    cio_gpio_q[31:16] == ((reg2hw.masked_out_upper.mask.q & reg2hw.masked_out_upper.data.q) | (~reg2hw.masked_out_upper.mask.q & pre_cio_gpio_q[31:16]));
  endproperty
  A_masked_write_data_upper: assert property (p_masked_write_data_upper);

  // SVA for Masked Write Verification (Data) Lower (LINE 4)
  property p_masked_write_data_lower;
    @(posedge clk_i) disable iff (!rst_ni)
    reg2hw.masked_out_lower.data.qe |=>
    cio_gpio_q[15:0] == ((reg2hw.masked_out_lower.mask.q & reg2hw.masked_out_lower.data.q) | (~reg2hw.masked_out_lower.mask.q & pre_cio_gpio_q[15:0]));
  endproperty
  A_masked_write_data_lower: assert property (p_masked_write_data_lower);

  //Helper logic for the current value of cio_gpio_en_q
  logic [31:0] pre_cio_gpio_en_q;
  always_ff @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      pre_cio_gpio_en_q <= '0;
    else 
      pre_cio_gpio_en_q <= cio_gpio_en_q;

  // SVA for Masked Write Verification (OE) Upper (LINE 7)
  property p_masked_write_oe_upper;
    @(posedge clk_i) disable iff (!rst_ni)
    reg2hw.masked_oe_upper.data.qe |=>
    cio_gpio_en_q[31:16] == ((reg2hw.masked_oe_upper.mask.q & reg2hw.masked_oe_upper.data.q) | (~reg2hw.masked_oe_upper.mask.q & pre_cio_gpio_en_q[31:16]));
  endproperty
  A_masked_write_oe_upper: assert property (p_masked_write_oe_upper);

  // SVA for Masked Write Verification (OE) Lower (LINE 8)
  property p_masked_write_oe_lower;
    @(posedge clk_i) disable iff (!rst_ni)
    reg2hw.masked_oe_lower.data.qe |=>
    cio_gpio_en_q[15:0] == ((reg2hw.masked_oe_lower.mask.q & reg2hw.masked_oe_lower.data.q) | (~reg2hw.masked_oe_lower.mask.q & pre_cio_gpio_en_q[15:0])));
  endproperty
  A_masked_write_oe_lower: assert property (p_masked_write_oe_lower);

  // SVA for Data Input Capture Verification (LINE 9)
  property p_data_in_capture;
    @(posedge clk_i) disable iff (!rst_ni)
    data_in_q == $past(data_in_d);
  endproperty
  A_data_in_capture: assert property (p_data_in_capture);

  //UC2: Reset De-assertion Verification
  //Property: After reset is deasserted, the GPIO module should be in a defined state (e.g., ready to accept configuration).
  property p_reset_deassertion;
    @(posedge clk_i) disable iff (!rst_ni)
    $rose(rst_ni) |=> reg2hw.direct_out.qe == 0 && reg2hw.direct_oe.qe == 0;
  endproperty
  A_reset_deassertion: assert property (p_reset_deassertion);

  //UC3: Direct Output Register Write:
  //Property: Writing different values (0 and 1) to the register that feeds reg2hw.direct_out.q results in the corresponding values being propagated to cio_gpio_q.
  property p_direct_output_write;
    @(posedge clk_i) disable iff (!rst_ni)
    reg2hw.direct_out.qe |=> cio_gpio_q == reg2hw.direct_out.q;
  endproperty
  A_direct_output_write: assert property (p_direct_output_write);

  //UC6: Direct Output Enable Register Write:
  //Property: writing different values (0 and 1) to the register that feeds reg2hw.direct_oe.q results in the corresponding values being propagated to cio_gpio_en_q.
  property p_direct_oe_register_write;
    @(posedge clk_i) disable iff (!rst_ni)
    reg2hw.direct_oe.qe |=> cio_gpio_en_q == reg2hw.direct_oe.q;
  endproperty
  A_direct_oe_register_write: assert property (p_direct_oe_register_write);

  //UC10: Clock Enable Verification:
  //Property: The clock should be running.
  property p_clock_is_running;
    @(posedge clk_i) disable iff (!rst_ni)
      clk_i == ~ $past(clk_i);
  endproperty
  A_clock_is_running: assert property (p_clock_is_running);

   //UC11: No Glitch Verification:
  //Property: Verify that the signals cio_gpio_q and cio_gpio_en_q do not glitch when the mask and data signals change. This ensures signal integrity.
generate
    genvar i;
    for (i = 0; i < 32; i++) begin : gen_no_glitch
      property p_no_glitch_gpio_q;
        @(posedge clk_i) disable iff (!rst_ni)
          $stable(cio_gpio_q[i]);
      endproperty
      A_no_glitch_gpio_q: assert property (p_no_glitch_gpio_q);

      property p_no_glitch_gpio_en_q;
        @(posedge clk_i) disable iff (!rst_ni)
          $stable(cio_gpio_en_q[i]);
      endproperty
      A_no_glitch_gpio_en_q: assert property (p_no_glitch_gpio_en_q);
    end 
endgenerate

  //UC18: Enable Signal Stability:
  //Property: Add assertions to verify that enable signals are stable during the relevant clock cycles. This prevents unintended behavior due to glitches or timing issues.
generate
  genvar i;
   for (i = 0; i < 32; i++) begin : gen_enable_stable
    property p_enable_signal_stable;
      @(posedge clk_i) disable iff (!rst_ni)
        $stable(reg2hw.ctrl_en_input_filter.q[i]);
    endproperty
    A_enable_signal_stable: assert property (p_enable_signal_stable);
   end
endgenerate

// Stage 1 AUTO-GENERATED ASSERTIONS END




endmodule

